# Generated by Django 4.2.2 on 2023-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipeingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.PositiveIntegerField(help_text='In minutes')),
                ('description', models.TextField(default='No description yet...')),
                ('difficulty', models.CharField(default='Difficulty not yet rated...', max_length=20)),
                ('ingredients', models.ManyToManyField(through='recipeingredients.RecipeIngredient', to='ingredients.ingredient')),
            ],
        ),
    ]
