# Generated by Django 4.2.2 on 2023-07-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch/Dinner', 'Lunch/Dinner'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], default='Lunch/Dinner', max_length=15),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='Difficulty not yet rated...', max_length=27),
        ),
    ]
